defaults :
  - modulus_default
  - arch:
      - fully_connected
      - fourier
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

jit: false

scheduler:
  decay_rate: 0.95
  decay_steps: 20000


training:
  rec_results_freq : 10000
  rec_constraint_freq: 5000
  max_steps : 100000

batch_size:
  interior: 512
  interior_init: 512
  initial_condition: 512
  inlet: 512
  outlet: 512
  wf_pt: 512
